### PR TITLE
Added an example dataset for the graph feature

### PR DESCRIPTION
**Pull request by ryotayamanaka**
I have added the first example dataset for graph feature.

It is the dataset used in this LiveLabs workshop:
https://apexapps.oracle.com/pls/apex/dbpm/r/livelabs/view-workshop?wid=770

### CODE REVIEW

**Comment by gvenzl** [comment]
@ryotayamanaka, why do you want to put sample data into this repository when it's already made available in OCI Object Store?

**Comment by ryotayamanaka** [comment]
@gvenzl, thank you for your review!

We would like to move the dataset to this repository because it is more convenient for both the users and the development than keeping it in OCI Object Store, with the following reasons:

- We (= data provider) can add README to describe the dataset
- We can sort out the datasets in one place in the future, with git tracking
- Users can check the contents before downloading the dataset
- Users can access each file using curl or wget easily

**Comment by ryotayamanaka** [comment]
@gvenzl I have also added "graph" entry to the table in README. Thank you!

**Comment by gvenzl** [comment]
Thanks a lot, @ryotayamanaka!

There seems to be a bigger effort going on right now with respect to:
* We can sort out the datasets in one place in the future, with git tracking

Git and GitHub are usually not the right places to manage large volumes of data.

Let me loop you into the conversations internally, then we can still decide whether or not to move forward with this here or somewhere else.

**Comment by ryotayamanaka** [comment]
We hope to follow the alternative solution you suggest. Let me close this request first.

**Pull request closed without merging**
